export const sampleData = {
  counters: {
    u_row: 22,
    u_column: 33,
    u_content_menu: 3,
    u_content_text: 38,
    u_content_image: 16,
    u_content_button: 4,
    u_content_social: 1,
    u_content_divider: 7,
    u_content_heading: 3,
    u_content_form: 1,
  },
  body: {
    id: 'vzkOi_VA9z',
    rows: [
      {
        id: '4Xo1X1qzvl',
        cells: [1],
        columns: [
          {
            id: '8CHjiXRKz_',
            contents: [
              {
                id: '1E4sDS47E3',
                type: 'form',
                values: {
                  containerPadding: '10px',
                  anchor: '',
                  action: { method: 'GET', target: '_self', url: '' },
                  fields: [
                    {
                      name: 'email',
                      type: 'email',
                      label: 'Email',
                      placeholder_text: 'Enter email here',
                      show_label: true,
                      required: true,
                    },
                    {
                      type: 'text',
                      name: 'password',
                      label: 'Password',
                      value: '',
                      options: '',
                      show_label: true,
                      placeholder_text: 'Enter password here',
                      required: true,
                    },
                  ],
                  fieldBorder: {
                    borderTopWidth: '1px',
                    borderTopStyle: 'solid',
                    borderTopColor: '#CCC',
                    borderLeftWidth: '1px',
                    borderLeftStyle: 'solid',
                    borderLeftColor: '#CCC',
                    borderRightWidth: '1px',
                    borderRightStyle: 'solid',
                    borderRightColor: '#CCC',
                    borderBottomWidth: '1px',
                    borderBottomStyle: 'solid',
                    borderBottomColor: '#CCC',
                  },
                  fieldBorderRadius: '0px',
                  fieldPadding: '10px',
                  fieldBackgroundColor: '#FFF',
                  fieldColor: '#000',
                  fieldFontSize: '12px',
                  formWidth: { autoWidth: false, width: '100%' },
                  formAlign: 'center',
                  fieldDistance: '10px',
                  labelFontSize: '14px',
                  labelColor: '#444',
                  labelAlign: 'left',
                  labelPadding: '0px 0px 3px',
                  buttonText: 'Login',
                  buttonColors: {
                    color: '#FFF',
                    backgroundColor: '#3AAEE0',
                    hoverColor: '#FFF',
                    hoverBackgroundColor: '#3AAEE0',
                  },
                  buttonAlign: 'center',
                  buttonWidth: { autoWidth: false, width: '100%' },
                  buttonFontSize: '14px',
                  buttonBorder: {},
                  buttonBorderRadius: '4px',
                  buttonPadding: '10px',
                  buttonMargin: '5px 0px 0px',
                  displayCondition: null,
                  _meta: {
                    htmlID: 'u_content_form_1',
                    htmlClassNames: 'u_content_form',
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  fieldWidth: '100%',
                },
              },
            ],
            values: {
              backgroundColor: '',
              padding: '0px',
              border: {},
              borderRadius: '0px',
              _meta: { htmlID: 'u_column_33', htmlClassNames: 'u_column' },
            },
          },
        ],
        values: {
          displayCondition: null,
          columns: false,
          backgroundColor: '',
          columnsBackgroundColor: '',
          backgroundImage: {
            url: '',
            fullWidth: true,
            repeat: 'no-repeat',
            size: 'custom',
            position: 'center',
          },
          padding: '0px',
          anchor: '',
          _meta: { htmlID: 'u_row_22', htmlClassNames: 'u_row' },
          selectable: true,
          draggable: true,
          duplicatable: true,
          deletable: true,
          hideable: true,
        },
      },
    ],
    headers: [],
    footers: [],
    values: {
      popupPosition: 'center',
      popupWidth: '600px',
      popupHeight: 'auto',
      borderRadius: '10px',
      contentAlign: 'center',
      contentVerticalAlign: 'center',
      contentWidth: '500px',
      fontFamily: {
        label: 'Arial',
        value: 'arial,helvetica,sans-serif',
        defaultFont: true,
      },
      textColor: '#08122c',
      popupBackgroundColor: '#FFFFFF',
      popupBackgroundImage: {
        url: '',
        fullWidth: true,
        repeat: 'no-repeat',
        size: 'cover',
        position: 'center',
      },
      popupOverlay_backgroundColor: 'rgba(0, 0, 0, 0.1)',
      popupCloseButton_position: 'top-right',
      popupCloseButton_backgroundColor: '#DDDDDD',
      popupCloseButton_iconColor: '#08122c',
      popupCloseButton_borderRadius: '0px',
      popupCloseButton_margin: '0px',
      popupCloseButton_action: {
        name: 'close_popup',
        attrs: {
          onClick:
            "document.querySelector('.u-popup-container').style.display = 'none';",
        },
      },
      backgroundColor: '#ffffff',
      preheaderText: '',
      linkStyle: {
        body: true,
        linkColor: '#4a90e2',
        linkHoverColor: '#4a90e2',
        linkUnderline: true,
        linkHoverUnderline: true,
      },
      backgroundImage: {
        url: '',
        fullWidth: true,
        repeat: 'no-repeat',
        size: 'custom',
        position: 'top-center',
        customPosition: ['50%', '0%'],
      },
      _meta: { htmlID: 'u_body', htmlClassNames: 'u_body' },
    },
  },
  schemaVersion: 16,
};
