export const sampleData = {
  counters: {
    u_row: 21,
    u_column: 32,
    u_content_menu: 3,
    u_content_text: 38,
    u_content_image: 16,
    u_content_button: 4,
    u_content_social: 1,
    u_content_divider: 7,
    u_content_heading: 3,
  },
  body: {
    id: 'vzkOi_VA9y',
    rows: [
      {
        id: 'GWm98NDEH6',
        cells: [1],
        columns: [
          {
            id: 'Fi544_IZb8',
            contents: [
              {
                id: '0OsZ54dDVK',
                type: 'image',
                values: {
                  containerPadding: '0px',
                  anchor: '',
                  src: {
                    url: 'https://storage.googleapis.com/kikkerprodbucket/images/welcome_mail_pay_before_delivery_ws_banner.png',
                    width: 600,
                    height: 210,
                  },
                  textAlign: 'center',
                  altText: 'welcome_mail_pay_before_delivery_ws_banner.png',
                  action: {
                    name: 'web',
                    values: {
                      href: '',
                      target: '_blank',
                    },
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: {
                    htmlID: 'u_content_image_16',
                    htmlClassNames: 'u_content_image',
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                },
              },
            ],
            values: {
              backgroundColor: '',
              padding: '0px',
              border: {},
              borderRadius: '0px',
              _meta: {
                htmlID: 'u_column_28',
                htmlClassNames: 'u_column',
              },
            },
          },
        ],
        values: {
          displayCondition: null,
          columns: false,
          backgroundColor: '',
          columnsBackgroundColor: '',
          backgroundImage: {
            url: '',
            fullWidth: true,
            repeat: 'no-repeat',
            size: 'custom',
            position: 'center',
          },
          padding: '0px',
          anchor: '',
          hideDesktop: false,
          _meta: {
            htmlID: 'u_row_19',
            htmlClassNames: 'u_row',
          },
          selectable: true,
          draggable: true,
          duplicatable: true,
          deletable: true,
          hideable: true,
        },
      },
      {
        id: 'hkFO2aqReq',
        cells: [1],
        columns: [
          {
            id: 'NeYf1DVTHJ',
            contents: [
              {
                id: 'hxYPCkP7zX',
                type: 'heading',
                values: {
                  containerPadding: '20px 0px 0px',
                  anchor: '',
                  headingType: 'h1',
                  fontSize: '18px',
                  color: '#08122c',
                  textAlign: 'left',
                  lineHeight: '140%',
                  linkStyle: {
                    inherit: true,
                    linkColor: '#0000ee',
                    linkHoverColor: '#0000ee',
                    linkUnderline: true,
                    linkHoverUnderline: true,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: {
                    htmlID: 'u_content_heading_3',
                    htmlClassNames: 'u_content_heading',
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<span style="line-height: 25.2px;"><span style="line-height: 25.2px;"><span style="line-height: 25.2px;"><span style="line-height: 25.2px;"><span style="line-height: 25.2px;"><span style="line-height: 25.2px;"><span style="line-height: 25.2px;"><span style="line-height: 25.2px;"><span style="line-height: 25.2px;"><span style="line-height: 25.2px;"><strong>Welkom bij [reseller_company_name]</strong></span></span></span></span></span></span></span></span></span></span>',
                  _override: {
                    mobile: {
                      containerPadding: '20px 15px 0px',
                    },
                  },
                },
              },
              {
                id: 'xXRxw1YFr6',
                type: 'text',
                values: {
                  containerPadding: '20px 0px 0px',
                  anchor: '',
                  fontSize: '12px',
                  color: '#08122c',
                  textAlign: 'right',
                  lineHeight: '140%',
                  linkStyle: {
                    inherit: true,
                    linkColor: '#0000ee',
                    linkHoverColor: '#0000ee',
                    linkUnderline: true,
                    linkHoverUnderline: true,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: {
                    htmlID: 'u_content_text_28',
                    htmlClassNames: 'u_content_text',
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<p style="line-height: 140%;"><span style="color: #08122c; line-height: 16.8px;">Contract nummer: [contract_number]</span></p>',
                  _override: {
                    mobile: {
                      containerPadding: '20px 15px 0px',
                    },
                  },
                },
              },
              {
                id: '7IoQAvz-BI',
                type: 'text',
                values: {
                  containerPadding: '15px 0px 0px',
                  anchor: '',
                  fontSize: '12px',
                  color: '#08122c',
                  textAlign: 'left',
                  lineHeight: '140%',
                  linkStyle: {
                    inherit: true,
                    linkColor: '#0000ee',
                    linkHoverColor: '#0000ee',
                    linkUnderline: true,
                    linkHoverUnderline: true,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: {
                    htmlID: 'u_content_text_13',
                    htmlClassNames: 'u_content_text',
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<p style="line-height: 140%;"><span style="color: #08122c; line-height: 16.8px;">Geachte [gender] [last_name],</span></p>',
                  _override: {
                    mobile: {
                      containerPadding: '15px 15px 0px',
                    },
                  },
                },
              },
              {
                id: 'Ae_OWF3yKE',
                type: 'text',
                values: {
                  containerPadding: '15px 0px 0px',
                  anchor: '',
                  fontSize: '12px',
                  color: '#08122c',
                  textAlign: 'left',
                  lineHeight: '140%',
                  linkStyle: {
                    inherit: false,
                    linkColor: '#0000ee',
                    linkHoverColor: '#0000ee',
                    linkUnderline: false,
                    linkHoverUnderline: true,
                    body: false,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: {
                    htmlID: 'u_content_text_15',
                    htmlClassNames: 'u_content_text',
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<p style="line-height: 140%;"><span style="color: #08122c; line-height: 16.8px;">Wij danken u voor uw keuze voor [reseller_company_name] als energieleverancier. Uw getekende energiecontract is succesvol door ons ontvangen en verwerkt. We waarderen het vertrouwen dat u in ons stelt.</span></p>',
                  _override: {
                    mobile: {
                      containerPadding: '15px 15px 0px',
                    },
                  },
                },
              },
              {
                id: 'TlMm25iZ8k',
                type: 'text',
                values: {
                  containerPadding: '15px 0px 0px',
                  anchor: '',
                  fontSize: '12px',
                  color: '#08122c',
                  textAlign: 'left',
                  lineHeight: '140%',
                  linkStyle: {
                    inherit: false,
                    linkColor: '#0000ee',
                    linkHoverColor: '#0000ee',
                    linkUnderline: false,
                    linkHoverUnderline: true,
                    body: false,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: {
                    htmlID: 'u_content_text_29',
                    htmlClassNames: 'u_content_text',
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<p style="line-height: 140%;">Uw energiecontract start per [mutation_date].</p>',
                  _override: {
                    mobile: {
                      containerPadding: '15px 15px 0px',
                    },
                  },
                },
              },
              {
                id: 'RGWy0w3ZIP',
                type: 'text',
                values: {
                  containerPadding: '15px 0px 0px',
                  anchor: '',
                  fontSize: '12px',
                  color: '#08122c',
                  textAlign: 'left',
                  lineHeight: '140%',
                  linkStyle: {
                    inherit: false,
                    linkColor: '#0000ee',
                    linkHoverColor: '#0000ee',
                    linkUnderline: false,
                    linkHoverUnderline: true,
                    body: false,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: {
                    htmlID: 'u_content_text_30',
                    htmlClassNames: 'u_content_text',
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<p style="line-height: 140%;"><strong>Mijn [reseller_name] Online</strong></p>',
                  _override: {
                    mobile: {
                      containerPadding: '15px 15px 0px',
                    },
                  },
                },
              },
              {
                id: 'kzba5gMREd',
                type: 'text',
                values: {
                  containerPadding: '15px 0px 0px',
                  anchor: '',
                  fontSize: '12px',
                  color: '#08122c',
                  textAlign: 'left',
                  lineHeight: '140%',
                  linkStyle: {
                    inherit: false,
                    linkColor: '#0000ee',
                    linkHoverColor: '#0000ee',
                    linkUnderline: false,
                    linkHoverUnderline: true,
                    body: false,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: {
                    htmlID: 'u_content_text_31',
                    htmlClassNames: 'u_content_text',
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<p style="line-height: 140%;"><span style="color: #08122c; line-height: 16.8px;">Een account voor Mijn [reseller_company_name] Online is voor u aangemaakt, waarmee u eenvoudig diverse energiezaken kunt regelen. Hierbij valt te denken aan het inzien van uw verbruik, het bekijken van facturen en het inzien van uw energietarieven.</span></p>',
                  _override: {
                    mobile: {
                      containerPadding: '15px 15px 0px',
                    },
                  },
                },
              },
              {
                id: 'f5XNlV-G0z',
                type: 'divider',
                values: {
                  width: '100%',
                  border: {
                    borderTopWidth: '1px',
                    borderTopStyle: 'solid',
                    borderTopColor: '#7cb928',
                  },
                  textAlign: 'center',
                  containerPadding: '20px 0px',
                  anchor: '',
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: {
                    htmlID: 'u_content_divider_7',
                    htmlClassNames: 'u_content_divider',
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                },
              },
              {
                id: 'nRiDx7VLHP',
                type: 'text',
                values: {
                  containerPadding: '0px',
                  anchor: '',
                  fontSize: '16px',
                  color: '#08122c',
                  textAlign: 'left',
                  lineHeight: '140%',
                  linkStyle: {
                    inherit: false,
                    linkColor: '#0000ee',
                    linkHoverColor: '#0000ee',
                    linkUnderline: false,
                    linkHoverUnderline: true,
                    body: false,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: {
                    htmlID: 'u_content_text_32',
                    htmlClassNames: 'u_content_text',
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<p style="line-height: 140%;"><span style="color: #08122c; line-height: 22.4px;"><strong>Account activatie</strong></span></p>',
                  _override: {
                    mobile: {
                      containerPadding: '0px 15px',
                    },
                  },
                },
              },
              {
                id: 'yZkI7H7JpK',
                type: 'text',
                values: {
                  containerPadding: '15px 0px 0px',
                  anchor: '',
                  fontSize: '12px',
                  color: '#08122c',
                  textAlign: 'left',
                  lineHeight: '140%',
                  linkStyle: {
                    inherit: false,
                    linkColor: '#0000ee',
                    linkHoverColor: '#0000ee',
                    linkUnderline: false,
                    linkHoverUnderline: true,
                    body: false,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: {
                    htmlID: 'u_content_text_33',
                    htmlClassNames: 'u_content_text',
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<p style="line-height: 140%;"><span style="color: #08122c; line-height: 16.8px;">U kunt uw account activeren door in te loggen met uw e-mailadres [customer_email] en gebruik te maken van de code <strong>[activation_code]</strong>.</span></p>',
                  _override: {
                    mobile: {
                      containerPadding: '15px 15px 0px',
                    },
                  },
                },
              },
            ],
            values: {
              backgroundColor: '',
              padding: '0px',
              border: {},
              borderRadius: '0px',
              _meta: {
                htmlID: 'u_column_18',
                htmlClassNames: 'u_column',
              },
            },
          },
        ],
        values: {
          displayCondition: null,
          columns: false,
          backgroundColor: '',
          columnsBackgroundColor: '',
          backgroundImage: {
            url: '',
            fullWidth: true,
            repeat: 'no-repeat',
            size: 'custom',
            position: 'center',
          },
          padding: '0px',
          anchor: '',
          hideDesktop: false,
          _meta: {
            htmlID: 'u_row_15',
            htmlClassNames: 'u_row',
          },
          selectable: true,
          draggable: true,
          duplicatable: true,
          deletable: true,
          hideable: true,
        },
      },
      {
        id: 'KBV4icOqJb',
        cells: [56.17, 43.83],
        columns: [
          {
            id: 'UVclcNx0_S',
            contents: [
              {
                id: '-hS5ELgBz0',
                type: 'text',
                values: {
                  containerPadding: '30px 20px 20px',
                  anchor: '',
                  fontSize: '16px',
                  color: '#06102e',
                  textAlign: 'left',
                  lineHeight: '140%',
                  linkStyle: {
                    inherit: true,
                    linkColor: '#0000ee',
                    linkHoverColor: '#0000ee',
                    linkUnderline: true,
                    linkHoverUnderline: true,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: {
                    htmlID: 'u_content_text_34',
                    htmlClassNames: 'u_content_text',
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<p style="line-height: 140%;"><strong>Mijn [reseller_company_name] Online</strong></p>',
                  _override: {
                    mobile: {
                      containerPadding: '30px 15px 20px',
                    },
                  },
                },
              },
              {
                id: 'O7Ad_XeqNl',
                type: 'text',
                values: {
                  containerPadding: '0px 20px 30px',
                  anchor: '',
                  fontSize: '12px',
                  color: '#08122c',
                  textAlign: 'left',
                  lineHeight: '140%',
                  linkStyle: {
                    inherit: false,
                    linkColor: '#4a90e2',
                    linkHoverColor: '#0000ee',
                    linkUnderline: false,
                    linkHoverUnderline: true,
                    body: false,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: {
                    htmlID: 'u_content_text_35',
                    htmlClassNames: 'u_content_text',
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<p style="line-height: 140%;"><span style="color: #08122c; line-height: 16.8px;">Via <a href="[reseller_my_workspace_url]" target="_self" data-u-link-value="eyJuYW1lIjoid2ViIiwiYXR0cnMiOnsiaHJlZiI6Int7aHJlZn19IiwidGFyZ2V0Ijoie3t0YXJnZXR9fSJ9LCJ2YWx1ZXMiOnsiaHJlZiI6IltyZXNlbGxlcl9teV93b3Jrc3BhY2VfdXJsXSIsInRhcmdldCI6Il9zZWxmIn19">[reseller_my_workspace_url]</a> activeert u direct uw [reseller_company_name] account.</span></p>',
                  _override: {
                    mobile: {
                      containerPadding: '0px 15px 30px',
                    },
                  },
                },
              },
            ],
            values: {
              backgroundColor: '#e5f1d4',
              padding: '0px',
              border: {
                borderTopWidth: '5px',
                borderTopStyle: 'solid',
                borderTopColor: '#83bb31',
                borderLeftWidth: '0px',
                borderLeftStyle: 'solid',
                borderLeftColor: '#CCC',
                borderRightWidth: '0px',
                borderRightStyle: 'solid',
                borderRightColor: '#CCC',
                borderBottomWidth: '0px',
                borderBottomStyle: 'solid',
                borderBottomColor: '#CCC',
              },
              borderRadius: '0px',
              _meta: {
                htmlID: 'u_column_29',
                htmlClassNames: 'u_column',
              },
            },
          },
          {
            id: 'tFhGnX-al3',
            contents: [],
            values: {
              backgroundColor: '',
              padding: '0px',
              border: {},
              borderRadius: '0px',
              _meta: {
                htmlID: 'u_column_32',
                htmlClassNames: 'u_column',
              },
            },
          },
        ],
        values: {
          displayCondition: null,
          columns: false,
          backgroundColor: '',
          columnsBackgroundColor: '',
          backgroundImage: {
            url: '',
            fullWidth: true,
            repeat: 'no-repeat',
            size: 'custom',
            position: 'center',
          },
          padding: '20px 0px 0px',
          anchor: '',
          hideDesktop: false,
          _meta: {
            htmlID: 'u_row_20',
            htmlClassNames: 'u_row',
          },
          selectable: true,
          draggable: true,
          duplicatable: true,
          deletable: true,
          hideable: true,
          _override: {
            mobile: {
              hideMobile: false,
              noStackMobile: false,
            },
          },
        },
      },
      {
        id: 'Srgl5_6iHC',
        cells: [1],
        columns: [
          {
            id: 'tIY-ZEBe-Q',
            contents: [
              {
                id: 'ayW0Xr5pTU',
                type: 'text',
                values: {
                  containerPadding: '20px 0px 0px',
                  anchor: '',
                  fontSize: '12px',
                  color: '#08122c',
                  textAlign: 'left',
                  lineHeight: '140%',
                  linkStyle: {
                    inherit: true,
                    linkColor: '#f0675c',
                    linkHoverColor: '#0000ee',
                    linkUnderline: true,
                    linkHoverUnderline: true,
                    body: false,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: {
                    htmlID: 'u_content_text_36',
                    htmlClassNames: 'u_content_text',
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<p style="line-height: 140%;"><span style="color: #08122c; line-height: 16.8px;"><strong data-renderer-mark="true">Betaling waarborg</strong></span></p>\n<p style="line-height: 140%;"><span style="text-decoration: underline; line-height: 16.8px;"><span style="color: #f0675c; line-height: 16.8px; text-decoration: underline;"><strong>Belangrijk</strong></span></span>: <span style="color: #08122c; line-height: 16.8px;">om te vermelden is dat uw contract pas definitief van start gaat nadat u de waarborgsom heeft voldaan. Deze factuur ontvangt u separaat in een later stadium per e-mail.</span></p>',
                  _override: {
                    mobile: {
                      containerPadding: '20px 15px 0px',
                    },
                  },
                },
              },
              {
                id: '4oT2skBdVP',
                type: 'text',
                values: {
                  containerPadding: '20px 0px 0px',
                  anchor: '',
                  fontSize: '12px',
                  color: '#08122c',
                  textAlign: 'left',
                  lineHeight: '140%',
                  linkStyle: {
                    inherit: false,
                    linkColor: '#f0675c',
                    linkHoverColor: '#0000ee',
                    linkUnderline: false,
                    linkHoverUnderline: true,
                    body: false,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: {
                    htmlID: 'u_content_text_37',
                    htmlClassNames: 'u_content_text',
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<p style="line-height: 140%;"><span style="color: #08122c; line-height: 16.8px;"><span style="line-height: 16.8px;">Mocht u nog vragen hebben, neem dan gerust contact met ons op via</span> </span><span style="color: #4a90e2; line-height: 16.8px;"><a rel="noopener" href="mailto:[reseller_email]" target="_blank" style="color: #4a90e2;" data-u-link-value="eyJuYW1lIjoiZW1haWwiLCJhdHRycyI6eyJocmVmIjoibWFpbHRvOnt7ZW1haWx9fT9zdWJqZWN0PXt7c3ViamVjdH19JmJvZHk9e3tib2R5fX0ifSwidmFsdWVzIjp7ImVtYWlsIjoiW3Jlc2VsbGVyX2VtYWlsXSIsInN1YmplY3QiOiIiLCJib2R5IjoiIn19">[reseller_email]</a></span><span style="color: #08122c; line-height: 16.8px;"> <span style="line-height: 16.8px;">of bel naar <a rel="noopener" href="tel:[reseller_phone]" target="_blank" style="color: #08122c;" data-u-link-value="eyJuYW1lIjoicGhvbmUiLCJhdHRycyI6eyJocmVmIjoidGVsOnt7cGhvbmV9fSJ9LCJ2YWx1ZXMiOnsicGhvbmUiOiJbcmVzZWxsZXJfcGhvbmVdIn19"><strong>[reseller_phone]</strong></a>.</span></span></p>',
                  _override: {
                    mobile: {
                      containerPadding: '20px 15px 0px',
                    },
                  },
                },
              },
              {
                id: '-tB42T_3Ee',
                type: 'text',
                values: {
                  containerPadding: '20px 0px 0px',
                  anchor: '',
                  fontSize: '12px',
                  color: '#08122c',
                  textAlign: 'left',
                  lineHeight: '140%',
                  linkStyle: {
                    inherit: true,
                    linkColor: '#f0675c',
                    linkHoverColor: '#0000ee',
                    linkUnderline: true,
                    linkHoverUnderline: true,
                    body: false,
                  },
                  hideDesktop: false,
                  displayCondition: null,
                  _meta: {
                    htmlID: 'u_content_text_38',
                    htmlClassNames: 'u_content_text',
                  },
                  selectable: true,
                  draggable: true,
                  duplicatable: true,
                  deletable: true,
                  hideable: true,
                  text: '<p style="line-height: 140%;"><span style="color: #08122c; line-height: 16.8px;">Met vriendelijke groet,</span></p>\n<p style="line-height: 140%;"><span style="color: #08122c; line-height: 16.8px;">[reseller_company_name]</span></p>',
                  _override: {
                    mobile: {
                      containerPadding: '20px 15px',
                    },
                  },
                },
              },
            ],
            values: {
              backgroundColor: '',
              padding: '0px',
              border: {},
              borderRadius: '0px',
              _meta: {
                htmlID: 'u_column_31',
                htmlClassNames: 'u_column',
              },
            },
          },
        ],
        values: {
          displayCondition: null,
          columns: false,
          backgroundColor: '',
          columnsBackgroundColor: '',
          backgroundImage: {
            url: '',
            fullWidth: true,
            repeat: 'no-repeat',
            size: 'custom',
            position: 'center',
          },
          padding: '0px',
          anchor: '',
          hideDesktop: false,
          _meta: {
            htmlID: 'u_row_21',
            htmlClassNames: 'u_row',
          },
          selectable: true,
          draggable: true,
          duplicatable: true,
          deletable: true,
          hideable: true,
        },
      },
    ],
    headers: [],
    footers: [],
    values: {
      popupPosition: 'center',
      popupWidth: '600px',
      popupHeight: 'auto',
      borderRadius: '10px',
      contentAlign: 'center',
      contentVerticalAlign: 'center',
      contentWidth: '600px',
      fontFamily: {
        label: 'Arial',
        value: 'arial,helvetica,sans-serif',
        defaultFont: true,
      },
      textColor: '#08122c',
      popupBackgroundColor: '#FFFFFF',
      popupBackgroundImage: {
        url: '',
        fullWidth: true,
        repeat: 'no-repeat',
        size: 'cover',
        position: 'center',
      },
      popupOverlay_backgroundColor: 'rgba(0, 0, 0, 0.1)',
      popupCloseButton_position: 'top-right',
      popupCloseButton_backgroundColor: '#DDDDDD',
      popupCloseButton_iconColor: '#08122c',
      popupCloseButton_borderRadius: '0px',
      popupCloseButton_margin: '0px',
      popupCloseButton_action: {
        name: 'close_popup',
        attrs: {
          onClick:
            "document.querySelector('.u-popup-container').style.display = 'none';",
        },
      },
      backgroundColor: '#ffffff',
      preheaderText: '',
      linkStyle: {
        body: true,
        linkColor: '#4a90e2',
        linkHoverColor: '#4a90e2',
        linkUnderline: true,
        linkHoverUnderline: true,
      },
      backgroundImage: {
        url: '',
        fullWidth: true,
        repeat: 'no-repeat',
        size: 'custom',
        position: 'top-center',
        customPosition: ['50%', '0%'],
      },
      _meta: {
        htmlID: 'u_body',
        htmlClassNames: 'u_body',
      },
    },
  },
  schemaVersion: 16,
};
